name: Pull Request Test

on:
  pull_request:
    types:
      # 当 feature 分支关闭时，
      - closed
    branches:    
      - feature-*

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      # 切出代码，使用该 Action 将可以拉取最新代码
      - uses: actions/checkout@v2
      - name: Stop Preview
        run: |
          cat preview.docker-compose.yaml | envsubst > docker-compose.yaml
          docker-compose stop
        env:
          COMMIT_REF_NAME: ${{ github.ref_name }}